-- =============================================
-- Script to create the wkl_users table
-- This table is designed to work with the generate_hashes.js script.
-- =============================================

-- It's a good practice to check if the table already exists.
-- If it does, this script will drop it before creating a new one.
IF OBJECT_ID('dbo.wkl_users', 'U') IS NOT NULL
DROP TABLE dbo.wkl_users;
GO

-- Create the wkl_users table structure
CREATE TABLE dbo.wkl_users (
    -- user_id: An auto-incrementing integer that serves as the primary key.
    user_id INT IDENTITY(1,1) PRIMARY KEY,
    
    -- username: Stores the user's login name. It must be unique.
    username NVARCHAR(50) NOT NULL UNIQUE,
    
    -- password_hash: Stores the hashed password generated by bcrypt. 
    -- It's NVARCHAR(255) to ensure it's long enough for bcrypt hashes.
    password_hash NVARCHAR(255) NOT NULL,
    
    -- created_at: Automatically records the timestamp when a user is created.
    created_at DATETIME DEFAULT GETDATE()
);
GO

PRINT 'Table "wkl_users" created successfully.';
GO

-- =============================================
-- HOW TO ADD USERS:
-- =============================================
-- 1. Run the `generate_hashes.js` script in your project using `node generate_hashes.js`.
-- 2. The script will output `INSERT` statements to the console.
-- 3. Copy those `INSERT` statements.
-- 4. Paste and run them in your SQL database management tool after running this create table script.
-- =============================================
